name: {{#snakeCase}}{{project_name}}{{/snakeCase}}
description: {{{description}}}
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=2.14.0 <3.0.0"

dependencies:
  bloc: ^7.2.1
  flutter:
    sdk: flutter
  flutter_bloc: ^7.3.1
  flutter_localizations:
    sdk: flutter
  intl: ^0.17.0

dev_dependencies:
  bloc_test: ^8.4.0
  flutter_test:
    sdk: flutter
  mocktail: ^0.2.0
  very_good_analysis: ^2.4.0

flutter:
  uses-material-design: true
  generate: true
