name: very_good_core
description: A Very Good App
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=2.18.0 <3.0.0"

dependencies:
  bloc: ^8.1.0
  cached_network_image: ^3.2.3
  chopper: ^6.0.0
  connectivity_plus: ^3.0.2
  crypto: ^3.0.2
  dartx: ^1.1.0
  dartz: ^0.10.1
  email_validator: ^2.1.17
  faker: ^2.1.0
  flash: ^2.0.5
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.1
  flutter_dotenv: ^5.0.2
  flutter_hooks: ^0.18.5+1
  flutter_localizations:
    sdk: flutter
  flutter_markdown: ^0.6.13
  flutter_secure_storage: ^7.0.1
  flutter_web_plugins:
    sdk: flutter
  freezed_annotation: ^2.2.0
  get_it: ^7.2.0
  go_router: ^6.0.1
  html_unescape: ^2.0.0
  http: ^0.13.5
  injectable: ^2.1.0
  intl: ^0.17.0
  intl_utils: ^2.7.0
  json_annotation: ^4.7.0
  logger: ^1.1.0
  path_provider: ^2.0.11
  pull_to_refresh_flutter3: ^2.0.1
  responsive_framework: ^0.2.0
  rxdart: ^0.27.7
  shared_preferences: ^2.0.15
  timeago: ^3.3.0
  url_launcher: ^6.1.5
  uuid: ^3.0.7
  webview_flutter: ^4.0.1

dev_dependencies:
  alchemist: ^0.5.1
  bloc_test: ^9.1.0
  build_runner: ^2.3.0
  chopper_generator: ^6.0.0
  dart_code_metrics: ^4.19.2
  dependency_validator: ^3.2.2
  flutter_gen: ^5.1.0+1
  flutter_gen_runner: ^5.1.0+1
  flutter_test:
    sdk: flutter
  freezed: ^2.2.0
  golden_toolkit: ^0.14.0
  injectable_generator: ^2.1.3
  json_serializable: ^6.5.4
  mockito: ^5.3.2
  mocktail_image_network: ^0.3.1
  very_good_analysis: ^3.1.0

flutter_gen:
  output: lib/app/generated/
  integration:
    flutter_svg: true

import_sorter:
  ignored_files:
    - \/lib\/*.g.dart
    - \/lib\/*.freezed.dart
    - \/lib\/*.config.dart
    - \/lib\/*.chopper.dart
    - \/lib\/*.mocks.dart

flutter_intl:
  enabled: true
  class_name: AppLocalizations
  arb_dir: assets/l10n/
  output_dir: lib/app/generated/

flutter:
  generate: true
  uses-material-design: true
  assets:
    - assets/images/
    - assets/icons/
    - assets/fonts/
    - assets/env/
