name: e2e
description: VeryGoodCore's end-to-end testing package.
publish_to: none

environment:
  sdk: ">=2.18.0 <3.0.0"

dev_dependencies:
  mason: ^0.1.0-dev.41
  path: ^1.8.3
  test: ^1.19.2
  very_good_analysis: ^3.1.0
