name: very_good_core

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

on:
  push:
    paths:
      - .github/workflows/very_good_core.yaml
      - "brick/**"
    branches:
      - main
  pull_request:
    paths:
      - .github/workflows/very_good_core.yaml
      - "brick/**"
    branches:
      - main

jobs:
  brick:
    defaults:
      run:
        working-directory: brick

    runs-on: ubuntu-latest

    steps:
      - name: ğŸ“š Git Checkout
        uses: actions/checkout@v4

      # TODO(alestiago): Run matrix on min supported Flutter version and latest
      - name: ğŸ¦ Setup Flutter
        uses: subosito/flutter-action@v2

      - name: ğŸ§± Mason Make
        run: |
          dart pub global activate mason_cli
          mason get
          mason make very_good_core -c config.json -o test --on-conflict overwrite

      - name: ğŸ“¦ Install Dependencies
        run: |
          dart pub global activate very_good_cli
          very_good packages get --recursive test/test_app

      - name: âœ¨ Check Formatting
        run: dart format --set-exit-if-changed test/test_app

      - name: ğŸ•µï¸ Analyze
        run: dart analyze --fatal-infos --fatal-warnings test/test_app

      - name: ğŸ§ª Run Tests
        run: |
          cd test/test_app
          very_good test -j 4 --recursive --optimization --coverage --test-randomize-ordering-seed random

      - name: ğŸ“Š Check Code Coverage
        uses: VeryGoodOpenSource/very_good_coverage@v2
        with:
          path: brick/test/test_app/coverage/lcov.info
