name: very_good_core

on:
  pull_request:
    paths:
      - ".github/workflows/very_good_core.yaml"
      - "src/my_app/lib/**"
      - "src/my_app/test/**"
      - "src/my_app/pubspec.yaml"
      - "tool/generator/**"
  push:
    branches:
      - main
    paths:
      - ".github/workflows/very_good_core.yaml"
      - "src/my_app/lib/**"
      - "src/my_app/test/**"
      - "src/my_app/pubspec.yaml"
      - "tool/generator/**"

jobs:
  build:
    uses: VeryGoodOpenSource/very_good_workflows/.github/workflows/flutter_package.yml@v1
    with:
      flutter_channel: stable
      flutter_version: 3.7.3
      working_directory: src/my_app

  spell-check:
    uses: VeryGoodOpenSource/very_good_workflows/.github/workflows/spell_check.yml@v1
    with:
      includes: |
        **/*.md
        !.brick/**/*.md
        .*/**/*.md
      modified_files_only: false
